"use client";
import { useEffect, useState } from "react";
import AdminLayout from "@/components/admin/AdminLayout";
import { auth } from "@/lib/firebase";

type Data = {activeNow:number;today:{users:number;views:number};sevenDays:{users:number;views:number};thirtyDays:{users:number;views:number};pages:{title:string;path:string;views:number}[];devices:{name:string;users:number}[];updatedAt:string};

export default function AdminAnalyticsPage() {
  const [data,setData]=useState<Data|null>(null);
  const [error,setError]=useState("");
  const [loading,setLoading]=useState(true);
  async function load(){setLoading(true);setError("");try{const user=auth.currentUser;if(!user)throw new Error("Please sign in again.");const token=await user.getIdToken();const response=await fetch("/api/admin/analytics",{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});const result=await response.json();if(!response.ok)throw new Error(result.error||"Unable to load Analytics.");setData(result)}catch(e){setError(e instanceof Error?e.message:"Unable to load Analytics.")}finally{setLoading(false)}}
  useEffect(()=>{void load()},[]);
  const cards=data?[["Active now",data.activeNow,"Last 30 minutes"],["Today",data.today.users,`${data.today.views} page views`],["Last 7 days",data.sevenDays.users,`${data.sevenDays.views} page views`],["Last 30 days",data.thirtyDays.users,`${data.thirtyDays.views} page views`]]:[];
  return <AdminLayout><main className="analytics"><header><div><h1>Website Analytics</h1><p>Genuine visitor data from Google Analytics 4</p></div><button onClick={load} disabled={loading}>{loading?"Loading…":"Refresh"}</button></header>{error&&<section className="error"><b>Analytics could not be loaded.</b><span>{error}</span><button onClick={load}>Try again</button></section>}{loading&&!data&&<section className="panel">Loading genuine visitor statistics…</section>}{data&&<><section className="cards">{cards.map(([label,value,note])=><article key={String(label)}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>)}</section><div className="tables"><section><h2>Popular pages · 30 days</h2>{data.pages.length?data.pages.map(p=><div className="row" key={`${p.path}-${p.title}`}><span><b>{p.title}</b><small>{p.path}</small></span><strong>{p.views}</strong></div>):<p>No page data yet.</p>}</section><section><h2>Devices · 30 days</h2>{data.devices.length?data.devices.map(d=><div className="row" key={d.name}><b>{d.name}</b><strong>{d.users}</strong></div>):<p>No device data yet.</p>}</section></div><p className="updated">Updated {new Date(data.updatedAt).toLocaleString("en-IN")}</p></>}</main><style jsx>{`.analytics{display:grid;gap:18px;max-width:1100px}header{display:flex;justify-content:space-between;align-items:center;gap:16px}h1{margin:0;color:#172b4d;font-size:25px}header p{margin:5px 0 0;color:#64748b}button{border:0;border-radius:8px;background:#2563eb;color:white;padding:10px 14px;font-weight:700;cursor:pointer}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.cards article,.tables section,.panel,.error{background:white;border:1px solid #e2e8f0;border-radius:13px;padding:18px}.cards span,.cards small{display:block;color:#64748b}.cards strong{display:block;margin:7px 0;font-size:29px;color:#172b4d}.tables{display:grid;grid-template-columns:2fr 1fr;gap:16px}.tables h2{font-size:17px;margin:0 0 12px}.row{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:11px 0;border-top:1px solid #eef2f7}.row span{min-width:0}.row b,.row small{display:block}.row span b{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.row small{color:#94a3b8;margin-top:3px}.error{display:grid;gap:8px;border-color:#fecaca;background:#fff7f7;color:#991b1b}.error button{width:max-content}.updated{text-align:right;color:#94a3b8;font-size:12px}@media(max-width:850px){.cards{grid-template-columns:repeat(2,1fr)}.tables{grid-template-columns:1fr}}@media(max-width:520px){header{align-items:flex-start}.cards article{padding:14px}.cards strong{font-size:24px}}`}</style></AdminLayout>;
}
