export const jobSubCategories = [
  "10th Pass Jobs",
  "+2 Jobs",
  "ITI Jobs",
  "Diploma Jobs",
  "Degree Jobs",
  "Govt Jobs",
  "Private Jobs",
  "Odisha Jobs",
  "Central Jobs",
  "Railway Jobs",
  "Banking Jobs",
  "Teaching Jobs",
  "Police Jobs",
  "Defence Jobs",
];